# Deploys new build in live
name: Deploy PR to live (test)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Enter release tag number (enter current to bump version)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "DeployLive"
  ChangeLog:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      # setting this flag so even if one job fails, others will continue
      fail-fast: false
      matrix:
        directory: ['deployment']

    # Steps represent a sequence of tasks that will be executed as part of the job
    # If latest, bump version
    steps:
      - run: npm ci

      - name: Validate version
        with:
          ref: v${{github.event.inputs.release_tag}}
        run: |
          pwd
          version=$(grep -E version ./package.json -m 1 | cut -c 15-19)
          echo $version
          if [[ ${{github.event.inputs.release_tag}} !=  $version ]]; then
            echo 'Previous version selected, continuing without changelog!';
            exit 1
          else
            echo 'Latest version selected!!';
          fi
      - name: Generate release notes
        run: npm run release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
