# Deploys new build in live
name: Output Test Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Enter release tag number'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: | 
        echo "{'name': 'app', 'version': '1.2.3'}" > test.json
        bar=$(echo $(cat test.json))
        echo "::set-output name=test::$bar"
    - id: step2
      uses: actions/github-script@v3.1.0
      env:
        data: ${{ steps.step1.outputs.test }}
      with:
        github-token: 1123
        script: |
          const fs = require('fs');
          const json = fs.readFileSync('./package.json', 'utf-8')
          console.log('result:', json)
      # run: |
      #   bumped_release_tag="4.1.1"
      #   echo "::set-output name=test::$bumped_release_tag"
      #   echo "New Release Tag: $bumped_release_tag"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}